### ISSUE TITLE
Results are capped at 50

### ISSUE THREAD

**Issue by camgas** [turbot/steampipe-plugin-twilio#18]
**Describe the bug**
All results are capped at 50. It seems it's set the MaxResult variable to 50. It would be nice if it is configurable. 

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**Comment by e-gineer** [comment]
Thanks for raising this @camgas - sorry you hit this bug.

It looks like we've done most of the work to setup for paging, but haven't done the actual page looping 😬 
 - https://github.com/turbot/steampipe-plugin-twilio/blob/main/twilio/table_twilio_account_message.go#L156-L218

PS: If you are on Steampipe v0.3.0 then I'd definitely recommend you upgrade to a later version! :-)

**Comment by camgas** [comment]
Correction, I am running steampipe version 0.16.4. Sorry about the wrong information above.

Thank you @e-gineer will watch for the pagination when it's done :) Love this plugin already!

**Comment by cbruno10** [comment]
Hey @camgas , sorry about that!

I just fixed this bug and released it in v0.3.1, can you please give it a try and let us know if you run into any issues?

I've also increased the page size to 1000 in most tables (except the serverless tables, as they're capped at 100), so hopefully performance is still quick when fetching hundreds or thousands of records.

**Comment by cbruno10** [comment]
For future reference, the way that the Twilio SDK handles paging internally is interesting, as they support `SetPageSize` and `SetLimit` functions, and then a page size is calculated based on these 2 values in https://github.com/twilio/twilio-go/blob/300974316779b187a25f13153bf3672a42cf4cc0/client/page_util.go#L9-L26.
